[package]
name = "nexa-runtime"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
getrandom.workspace = true
nexa-harness.workspace = true
nexa-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
