[package]
name = "nexa-tui"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crossterm.workspace = true
futures-util.workspace = true
nexa-client.workspace = true
nexa-protocol.workspace = true
ratatui.workspace = true
tokio.workspace = true

[lints]
workspace = true
