[package]
name = "nexa-cli"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "nexa"
path = "src/main.rs"

[dependencies]
crossterm.workspace = true
dirs.workspace = true
nexa-client.workspace = true
nexa-harness.workspace = true
nexa-protocol.workspace = true
nexa-tui.workspace = true
rpassword.workspace = true
tokio.workspace = true

[lints]
workspace = true
